build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:22.04
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:22.04
  armhf: ghcr.io/hassio-addons/ubuntu-base/armhf:22.04
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:22.04
  i386: ghcr.io/hassio-addons/ubuntu-base/i386:22.04