name: "Person Detector"
description: "Detect people in camera feeds using Edge Impulse"
version: "1.0.0"
slug: "person_detector"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  camera_entity: camera.basement_ai_cam_basement_ai_cam
  confidence_threshold: 0.7
  scan_interval: 1
  edge_impulse_api_key: "ei_d274e81230b26adbf50d93ac61dd8c602a80103a6150ea3231745e2f22871e73"
schema:
  camera_entity: str
  confidence_threshold: float(0,1)
  scan_interval: int(1,60)
  edge_impulse_api_key: str
environment:
  CAMERA_ENTITY: "{{ options.camera_entity }}"
  CONFIDENCE_THRESHOLD: "{{ options.confidence_threshold }}"
  SCAN_INTERVAL: "{{ options.scan_interval }}"
  EDGE_IMPULSE_API_KEY: "{{ options.edge_impulse_api_key }}"