name: "Edge Impulse Person Detector"
description: "Detects people using ESP32-CAM and Edge Impulse model"
version: "0.1.0"
slug: "edge_impulse_person_detector"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto

options:
  mqtt_broker: core-mosquitto
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  detection_threshold: 0.5
  person_detection_topic: "homeassistant/binary_sensor/person_detection/state"
  confidence_topic: "homeassistant/sensor/detection_confidence/state"

schema:
  mqtt_broker: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
  detection_threshold: float(0.1,1)
  person_detection_topic: str
  confidence_topic: str

host_network: true