name: "Edge Impulse Person Detector"
version: "1.0.0"
slug: "edge_impulse_person_detector"
description: Person detection using Edge Impulse"
url: "https://github.com/MusicMano/ha-person-detector"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
map:
  - config:rw
options:
  camera_entity: "camera.esp32_cam"
  confidence_threshold: 0.7
  scan_interval: 1
schema:
  camera_entity: str
  confidence_threshold: float
  scan_interval: 1
services:
  - mqtt:need
advanced: true
hassio_api: true
hassio_role: default
